### ISSUE TITLE
Distinguish between user-initiated and inertial mousewheel events

### ISSUE THREAD

**Issue by mikehwagz** [baptistebriel/slider-manager#3]
If inertial mousewheel events continue to fire after the animation is complete, the callback is called twice for one user-initiated scroll. Even when the animation is 1s long, for example, inertial mousewheel events sometimes still cause a second callback to occur.

Is this something that anyone has experienced? If so, does anyone have any solutions? Thanks in advance.

**Comment by baptistebriel** [comment]
Hey @mikehwagz,

We could use [virtual-scroll](https://github.com/ayamflow/virtual-scroll) instead of hamsterjs for mousewheel events and use the `limitInertia` option. I currently don't have much time to update it but I'll make sure to do so rapidly!

Thanks for pointing this out!

**Comment by mikehwagz** [comment]
Thanks for the quick response - that's a great solution. If I find some free time, maybe I'll take a stab at implementing virtual-scroll and make PR.

**Comment by mikehwagz** [comment]
@baptistebriel So I've managed to implement virtual-scroll to resolve the issue in my project, but I haven't been able to test properly. How do you usually go about testing this module? If possible, I'd like to run the same test suite before making a PR.

**Comment by baptistebriel** [comment]
Hey @mikehwagz,
I don't have a test suite for this module. If you have any ideas, feel free to implement!
Thanks a lot for looking into this. Let me know!

**Comment by baptistebriel** [comment]
I followed your work and it's now using `virtual-scroll` for mobile devices as well.
We were just listening to the swipe delta, and that could be done with the same module.
That makes the build files smaller! 💯

**Comment by mikehwagz** [comment]
@baptistebriel 🙌🏼
