### ISSUE TITLE
Wrong up and down on mouse scroll

### ISSUE THREAD

**Issue by mariosmaselli** [baptistebriel/slider-manager#4]
Hey man! me here again.. 

I've been using an old version from slider-manager (1.0.9) and everything was fine. But I updated to the latest one and I find a weird behavior on mouse scroll (using magic mouse) 

The mouse up is mouse down and mouse down is mouse up, it looks that they are inverted.

Here is a demo on 1.0.9 http://codepen.io/mariosmaselli/full/197f4892ff8d91b883e82a0dc1d6be0e/

Same demo on 1.1.1  http://codepen.io/mariosmaselli/full/41d301298553ae73927d67188d4032a4/

Thanks a lot for your work!

**Comment by baptistebriel** [comment]
Thanks for pointing this out @mariosmaselli! It should be fixed as of `slider-manager@1.1.5`.
Let me know if it's good on you end.

**Comment by baptistebriel** [comment]
I just fixed the horizontal behavior as it was inverted as well.
Should be all fine with either `x` or `y` direction! Feel free to re-open the issue if needed.
